### ISSUE TITLE
Composer installation error

### ISSUE THREAD

**Issue by EsoftsLimited** [omnilight/yii2-scheduling#10]
I get the following error kindly assist

Your requirements could not be resolved to an installable set of packages.        

  Problem 1
    - Conclusion: don't install omnilight/yii2-scheduling dev-master
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.6
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.5
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.3
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.2
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.1
    - Conclusion: remove symfony/process 3.1.x-dev
    - Installation request for omnilight/yii2-scheduling * -> satisfiable by omnilight/yii2-scheduling[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.0.6, dev-master].
    - Conclusion: don't install symfony/process 3.1.x-dev
    - omnilight/yii2-scheduling 1.0.0 requires symfony/process 2.6.* -> satisfiable by symfony/process[2.6.x-dev, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - Can only install one of: symfony/process[2.6.x-dev, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.0, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.0-BETA1, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.0-BETA2, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.1, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.10, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.11, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.12, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.13, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.2, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.3, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.4, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.5, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.6, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.7, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.8, 3.1.x-dev].
    - Can only install one of: symfony/process[v2.6.9, 3.1.x-dev].
    - Installation request for symfony/process == 3.1.9999999.9999999-dev -> satisfiable by symfony/process[3.1.x-dev].

**Comment by omnilight** [comment]
In your (or some of your components) composer.json exists requirements of the symfony/process with version ~3.1, this library requires 2.6.* - that's the problem

**Comment by nageshmohale** [comment]
I get same error.please kindly help us to fix this

ERROR:-

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.7
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.6
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.5
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.3
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.2
    - Conclusion: don't install omnilight/yii2-scheduling 1.0.1
    - Installation request for omnilight/yii2-scheduling * -> satisfiable by omnilight/yii2-scheduling[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.0.6, 1.0.7].
    - Conclusion: don't install symfony/process v3.3.6
    - omnilight/yii2-scheduling 1.0.0 requires symfony/process 2.6.* -> satisfiable by symfony/process[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - Can only install one of: symfony/process[v2.6.0, v3.3.6].
    - Can only install one of: symfony/process[v2.6.1, v3.3.6].
    - Can only install one of: symfony/process[v2.6.10, v3.3.6].
    - Can only install one of: symfony/process[v2.6.11, v3.3.6].
    - Can only install one of: symfony/process[v2.6.12, v3.3.6].
    - Can only install one of: symfony/process[v2.6.13, v3.3.6].
    - Can only install one of: symfony/process[v2.6.2, v3.3.6].
    - Can only install one of: symfony/process[v2.6.3, v3.3.6].
    - Can only install one of: symfony/process[v2.6.4, v3.3.6].
    - Can only install one of: symfony/process[v2.6.5, v3.3.6].
    - Can only install one of: symfony/process[v2.6.6, v3.3.6].
    - Can only install one of: symfony/process[v2.6.7, v3.3.6].
    - Can only install one of: symfony/process[v2.6.8, v3.3.6].
    - Can only install one of: symfony/process[v2.6.9, v3.3.6].
    - Installation request for symfony/process (locked at v3.3.6) -> satisfiable by symfony/process[v3.3.6].


Installation failed, reverting ./composer.json to its original content.

**Comment by gietos** [comment]
https://github.com/omnilight/yii2-scheduling/pull/20
