### ISSUE TITLE
PHP Fatal error:  Non-static method

### ISSUE THREAD

**Issue by lomion69** [omnilight/yii2-scheduling#17]
PHP Fatal error:  Non-static method yii\base\BaseObject::__construct() cannot be called statically, assuming $this from incompatible context in /Library/WebServer/sko4.dev/vendor/omnilight/yii2-scheduling/CallbackEvent.php on line 37
PHP Fatal Error 'yii\base\ErrorException' with message 'Non-static method yii\base\BaseObject::__construct() cannot be called statically, assuming $this from incompatible context'

in /Library/WebServer/sko4.dev/vendor/omnilight/yii2-scheduling/CallbackEvent.php:37

**Comment by gietos** [comment]
Please, show code of schedule.php

**Comment by lomion69** [comment]
<?php

namespace console\controllers;

use frontend\models\Log;
use Yii;
use omnilight\scheduling\ScheduleController;

/**
 * Cron tasks
 */
class CronController extends ScheduleController
{
    /**
     * Runs all cron tasks
     */
    public function actionRun()
    {
        $this->schedule
            ->call([$this, 'runMinutely'])
            ->description('Minutely tasks')
            ->cron('* * * * *');
        parent::actionRun();
    }

    /**
     * Minutely tasks
     */
    public function runMinutely()
    {
        $model = new Log();
        $model->text = date('Y-m-d H:m:s');
        $model->save();
    }
}

**Comment by lomion69** [comment]
`namespace console\controllers;

use frontend\models\Log;
use Yii;
use omnilight\scheduling\ScheduleController;

/**
 * Cron tasks
 */
class CronController extends ScheduleController
{
    /**
     * Runs all cron tasks
     */
    public function actionRun()
    {
        $this->schedule
            ->call([$this, 'runMinutely'])
            ->description('Minutely tasks')
            ->cron('* * * * *');
        parent::actionRun();
    }

    /**
     * Minutely tasks
     */
    public function runMinutely()
    {
        $model = new Log();
        $model->text = date('Y-m-d H:m:s');
        $model->save();
    }
}`

**Comment by lomion69** [comment]
even this one:

`$this->schedule
            ->call(function(){
                echo "Hello here";
            })
            ->everyMinute();`

**Comment by lomion69** [comment]
Please, push your commit to master/dev )

**Comment by gietos** [comment]
https://github.com/omnilight/yii2-scheduling/pull/21
