### ISSUE TITLE
Scheduler running, but cron() not working unless set to cron('* * * * *')

### ISSUE THREAD

**Issue by jonny7** [omnilight/yii2-scheduling#25]
Hi

I think this is a great package and I'm looking forward to utilizing it within my Yii2 module. I'm using windows and have a job running every minute that is this: 

>C:\xampp-7\htdocs\yii.bat schedule/run --scheduleFile=C:\xampp7\htdocs\modules\console\commands\schedule.php

In my Module.php I bootstrapped the Scheduler:

```
public function bootstrap($app)
    {
        if ($app instanceof \yii\console\Application) {
            $this->controllerNamespace = 'app\modules\console\commands';
            // https://github.com/omnilight/yii2-scheduling#how-to-use-this-extension-in-your-own-extension
            if ($app->has('schedule')) {
                /** @var omnilight\scheduling\Schedule $schedule */
                $schedule = $app->get('schedule');
            }
        }
    }
```

I have a commands folder within my console module and have schedule.php in there:
```
<?php
$schedule->command('console/command/hello -- DDDD 123')->cron('* * * * *');
```

Now if the job is put with the above cron config, it executes every time my windows task runs, which is every minute.

If I change the cron format to: `cron(1 * * * *)` then the job never seems to run. I'm sure this is me misconfiguring something, but not sure what? Any help would be greatly appreciated!

**Comment by gietos** [comment]
Your cron definition `1 * * * *` means `every hour on 1st minute`

See http://www.nncron.ru/help/EN/working/cron-format.htm for details

**Comment by jonny7** [comment]
Thanks @gietos ! Works all good now
