### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by skrajewski** [omnilight/yii2-scheduling#26]
Hello!

Thanks for this library, it looks really nice! Could you please add an information about the license of this project? Without the proper license, it's impossible to use it in other projects because of legal restrictions. This page could be very helpful: https://choosealicense.com/

Thanks a lot!

**Comment by tyler-ham** [comment]
Is there anything holding up a decision here? I am considering using this library but need clarity on the license first.

**Comment by omnilight** [comment]
Use it freely for your profit/non-profit projects, for personal or commercial use
