### ISSUE TITLE
Online Dashboard for scheduled tasks

### ISSUE THREAD

**Issue by philippfrenzel** [omnilight/yii2-scheduling#3]
Hi, what do you think about an online dashboard to see log information about executed scheduled tasks?

* Task
* Last run
* Next run
* Current status
* ...

Thanks Philipp

**Comment by omnilight** [comment]
What is use case of it? This extension provide a way to store all your crontasks in the git repository with your project.
Of couse it is possible to create dashboard, but I don't think that it should be part of this extension

**Comment by philippfrenzel** [comment]
hmm, maybe you are right... can you send events which can be triggered? So I can implement this by myself?

**Comment by omnilight** [comment]
It is possible to add events, I will think about it

**Comment by omnilight** [comment]
Added this in v.1.0.4

**Comment by philippfrenzel** [comment]
Great! Thanks!
