### ISSUE TITLE
symfony/process locked dependency problem

### ISSUE THREAD

**Issue by vishuB** [omnilight/yii2-scheduling#33]
Using composer install to get error Installation request for omnilight/yii2-scheduling * -> satisfiable by omnilight/yii2-scheduling[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1.0]

show below image

![omnilight_yii2_scheduling 1](https://user-images.githubusercontent.com/13677102/42804057-717b0b9c-89c5-11e8-9075-d0670d0c56a6.png)

Ubuntu : 16.04 LTS
Yii2 Version : 2.0.15.1
PHP Version : 7.1

**Comment by vishuB** [comment]
right

**Comment by vishuB** [comment]
your extention work perfect in symfony/process v4.1.1.

**Comment by omnilight** [comment]
@gietos We should just change requirement in composer json to
`"symfony/process": "^2.8 || ^3.4 || ^4.0"`
or something like that

**Comment by zeevy** [comment]
Still facing the similar issue 
```
Installation request for symfony/console (locked at v4.4.8) -> satisfiable by symfony/console[v4.4.8].
```
