### ISSUE TITLE
everyMinute() is missing

### ISSUE THREAD

**Issue by mjwvb** [omnilight/yii2-scheduling#4]
The method everyMinute() for scheduling is missing. It exists in Laravels component, so would be nice if you could implemented!

Not a big problem as you can use ->cron('* * * * * *') of course, but ok

**Comment by omnilight** [comment]
Added method for consistency, but you should know, that when you're simple creating new event, it's by default runs every minute

**Comment by mjwvb** [comment]
Aah ok, I wasn't aware of that. Thanks!
