### ISSUE TITLE
Требуемая версия PHP

### ISSUE THREAD

**Issue by templton** [omnilight/yii2-scheduling#47]
В composer.json указана версия
"php": ">=5.4.0"

но в последнем релизе добавлен метод
public function omitErrors(bool $omitErrors = false)
указывать hint bool можно в php с версии 7

В результате на моей системе с php 5.9 данный компонент устанавливается, но при работе отваливается из-за **hint bool** 

Предлагаю объявить данный метод так:
public function omitErrors($omitErrors = false)
то есть убрать hint bool

**Comment by gietos** [comment]
Thank you for your report. That is a bug. Please feel free to create a PR.

**Comment by gietos** [comment]
https://github.com/omnilight/yii2-scheduling/pull/48
