### ISSUE TITLE
Set default 'from' mailaddress

### ISSUE THREAD

**Issue by BBrunekreeft** [omnilight/yii2-scheduling#7]
I use Swift_SmtpTransport as mailprovider for swiftmailer, 
When using this code:
`$schedule->command('foo')->sendOutputTo($filePath)->emailOutputTo('foo@example.com');`
the following error occurres:

> Exception 'Swift_TransportException' with message 'Cannot send message without a sender address'

There should be a way to provide a from-address to the emailOutputTo method in the Event Class.

**Comment by AnatolyRugalev** [comment]
@BBrunekreeft you can use `$messageConfig` attribute in base application configuration to set default sender.

```php
'components' => [
  'mailer' => [
    'messageConfig' => [
      'from' => 'from@example.com'
    ]
  ]
]
```

**Comment by BBrunekreeft** [comment]
This works. Thanks!
