### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gav26512** [omnilight/yii2-scheduling#71]
Running scheduled command: /usr/local/bin/php yii delayed-message/check > /dev/null
2022-05-16 16:33:55 [0] /etc/nginx/html/vendor/symfony/process/Process.php (143)
> TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /etc/nginx/html/vendor/omnilight/yii2-scheduling/src/Event.php on line 145

name     : symfony/process
descrip. : Executes commands in sub-processes
keywords : 
versions : * v5.4.8

name     : omnilight/yii2-scheduling
descrip. : Scheduling extension for Yii2 framework
keywords : cron, scheduling, yii
versions : * 1.1.5

**Comment by omnilight** [comment]
Support removed in 1.1.6, as we need to refactor code to support symfony 5.x

If you can provide pr with fix - that would be great

**Comment by WHITE-developer** [comment]
@omnilight any updates on this [PR](https://github.com/omnilight/yii2-scheduling/pull/73)?
